This is the completed Sign Up page
AMBU-The-Unified-HealthCare-System/Ambu-Web-App pull request #14
Opened 2023-06-22 16:14 UTC by Pal-prakash

@Ash-2k3 Sir, I have completed my page, ready for review. I faced some issues with setting up the env though.

https://github.com/AMBU-The-Unified-HealthCare-System/Ambu-Web-App/assets/120311694/d4cb4f48-991e-43a2-9317-4dc3dbfd3c7d

2023-06-22 16:43 UTC, Ash-2k3 commented
Thanks @Pal-prakash, can you also add a screen-recording of mobile view (smaller screens). I will start review once you have added it.

2023-06-23 02:43 UTC, Pal-prakash commented
@Ash-2k3 Sir I added the mobile view.
https://github.com/AMBU-The-Unified-HealthCare-System/Ambu-Web-App/assets/120311694/849e9113-5fcd-461c-988b-2820afee2f27

2023-06-23 07:01 UTC, Ash-2k3 commented
Thanks @Pal-prakash.
 Deferring to @Yash080902 for design and responsiveness approval, If it looks good to him. I will start reviewing code.

2023-06-23 19:01 UTC, Ash-2k3 requested changes
Left some comments, PTAL

2023-06-23 19:02 UTC, Ash-2k3 commented on app/__init__.py
> +    return app
Please get rid of whitespaces and blanks lines here and elsewhere too. Please follow this for all the files and tag me once it's done, Thanks

2023-06-24 14:11 UTC, Ash-2k3 requested changes
Thanks, left some comments, PTAL.

2023-06-24 14:11 UTC, Ash-2k3 commented on app/controller/controllers.py
> +@get_Sign_Up.route('/Sign_Up')
Are you sure it's working ? I can't see `get_Sign_up` declared. You can take reference of `get_index_bp` above in line 7

2023-06-24 14:34 UTC, Pal-prakash commented
@Ash-2k3 i made changes. Sorry for missing it

2023-06-24 14:43 UTC, Ash-2k3 commented
Thanks @Pal-prakash. Also just a note: Please don't resolve the comments by yourself, let the reviewers do it once they are satisified wid your changes. This helps in keeping track of the changes they asked :)

2023-06-24 14:47 UTC, Ash-2k3 requested changes
Thanks, left some minor comments. Otherwise this looks good and can get merged once you have finished addressing these minor comments

2023-06-24 14:47 UTC, Ash-2k3 commented on app/controller/controllers.py
> +@get_Sign_Up.route('/Sign_Up')
No, this is not quite correct, please declare the variables above, after line 7.

2023-06-24 14:47 UTC, Ash-2k3 commented on app/templates/Sign_Up.html
> +
Nit: Remove the whitespace

2023-06-24 14:47 UTC, Ash-2k3 commented on app/templates/Sign_Up.html
> +
Same here, remove the whitespace

2023-06-25 06:32 UTC, Pal-prakash commented
@Ash-2k3 Sir, I removed all whitespaces

2023-06-25 07:43 UTC, Ash-2k3 commented
Thanks @Pal-prakash, LGTM !!

2023-06-25 07:43 UTC, Ash-2k3 approved these changes

2023-06-25 07:50 UTC, merged